http:
  address: "0.0.0.0:8080"

  uploads:
    forbid: [".php", ".exe", ".bat"]

  workers:
    command: "php bin/console baldinof:roadrunner:worker"
    relay: "unix://var/roadrunner.sock"
    relayTimeout: 30000000000

  rpc:
    enable: true
    listen: unix://var/roadrunner_rpc.sock

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]
